### ISSUE TITLE
java code doesn't run

### ISSUE THREAD

**Issue by YoYoChintu** [pushkar8723/Aurora#10]
Whenever i submit java solution, it shows could not find Main class.. however on running exact same commands as script executes on terminal, I get proper result

**Comment by pushkar8723** [comment]
For java code to run you need to write your program inside 'Main' class.
See http://aurora.pushkaranand.com/viewsolution/4 for example.

**Comment by YoYoChintu** [comment]
that one doesnt run, it says it could not find Main class

**Comment by pushkar8723** [comment]
Can you paste the error displayed on both ui and logs from judge?

**Comment by YoYoChintu** [comment]
The error.txt shows :
NZEC || return code 1
could not find or load main class Main..

The terminal returns RTE with exit code 1..

However when I run same commands as judge executes , I get output written to output.txt

**Comment by pushkar8723** [comment]
So compilation went fine. This means the Main.class is not generated or is not accessible. Check env folder for the files and their permission. Also paste the same here.

**Comment by YoYoChintu** [comment]
I set up chroot jail, basically did everything as said in readme.. the env folder is accessible by uid and gid 'judge' ..

every language works except java.. I have java7 but that shouldn't be an issue I think

**Comment by pushkar8723** [comment]
It seems that you haven't mount /proc to jail's proc. Use following command to mount it.
```
# mount -o bind /proc /path/to/chroot/proc
```
**Note :** You have to mount /proc each time you restart your system.
