### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alexbagirov** [pushkar8723/Aurora#7]
Hello.

I have installed Web Interface and it works just fine. Now I have entered `/var/www/aurora/Judge` folder on my Ubuntu and want to install Python scripts. Instruction says I have to input a `/path/to/chroot`. Where can I find it?

Also how can I enter that jail and exit it? How to run Aurora as daemon?

**Comment by pushkar8723** [comment]
Hi alex,

You can find the detailed steps of how to setup chroot jail in the readme file https://github.com/pushkar8723/Aurora/blob/master/Judge/README.md
If you want to know how chroot works you can watch https://www.youtube.com/watch?v=XTyY3in5r6Q

If you are feeling lazy, you can also execute https://github.com/pushkar8723/Aurora/blob/master/Judge/debian_setup.sh to setup judge automatically. Although i didn't test this script thoroughly but it should work in most cases.
On successful completion of the setup, this script will ask to execute one command to configure python script for db access. Just read the output at the end you will know what to do. :)
If you use this script, 'startjudge' command will be installed in /usr/bin folder which will start the judge.
To stop it, just press CTRL+C.

**Note:** Setting up jail is completely optional, you can run the python script in a virtual environment also using virtualbox or vmware. If you prefer virtual environment method then you just need to execute commands given in Readme file for compiler setup, security and configuring python script for db access.

I am closing this issue, but if you still face some problem, feel free to reopen.

**Comment by alexbagirov** [comment]
Ok, I am trying to use debian_setup.sh. It asks for target folder. What is it?

**Comment by pushkar8723** [comment]
Place where you want to setup the jail like
/opt/judge

**Comment by alexbagirov** [comment]
Thanks. Currently is it downloading packages :)

**Comment by alexbagirov** [comment]
I have made something incorrect and want to reinstall it. How can I delete a user that your scripts has created?

**Comment by pushkar8723** [comment]
The script creates a jail and user is created inside that jail.
To undo all changes done by the script just delete the Jail folder and /usr/bin/startjude.

**Comment by alexbagirov** [comment]
I can't delete Jail folder. It says 'Permission denied'. Maybe because of chown.

**Comment by alexbagirov** [comment]
Ok, I tried to install it and it asked me to edit variables in judge.py files. I was lokking for it, but it doesn't exist. Can you help me installing Aurora if I give you my SSH credentials by email, please?

**Comment by pushkar8723** [comment]
You are getting permission denied because the folder was created by root user and can be deleted only by root user.
To delete the jail use following commands
sudo rm -rf /path/to/jail/*
sudo rmdir /path/to/jail

Also variables are there in judge.py exactly on lines 14 to 19.
Try once more, before sharing your ssh creds with. Also if you share, please mention the directory where you installed the jail.

**Comment by alexbagirov** [comment]
Can you help me installing it from the beginning, please?

**Comment by pushkar8723** [comment]
OK, email me the problem.
