### ISSUE TITLE
Cannot do anything after logging in as judge

### ISSUE THREAD

**Issue by vozille** [pushkar8723/Aurora#8]
Say I want to view judge settings, I clicked on that, and it took me to http://localhost/Interface/adminjudge
which ofcourse doesnt exist. Same with all other options like creating a new account to adding problem set.

Replaced Web Interface as Interface , everyting else is same

**Comment by pushkar8723** [comment]
Seems like your apache's rewrite module is not loaded.
Go through the readme file and see if there is something you missed.
https://github.com/pushkar8723/Aurora/blob/master/Web%20Interface/README.md

**Comment by vozille** [comment]
Hi, I have the mod_rewrite enabled in var/www/html folder, where the files reside, still get 404

**Comment by pushkar8723** [comment]
mod_rewrite is apache level mod and you have to edit httpd.conf in /etc/apache2/ or /etc/httpd/conf/ depending on your distro.

**Comment by vozille** [comment]
I'm sorry, what I meant was that phpinfo in that folder shows mod_rewrite is enabled. 

I had enabled it using a2enmod command in terminal

**Comment by pushkar8723** [comment]
then your rewrite is not happening properly. Is config.php configured properly. You have to provided base path in SITE_URL variable.
define("SITE_URL", "http://" . $_SERVER['HTTP_HOST'] . "/aurora");

**Comment by vozille** [comment]
yes, I think it is, else I would not have been able to log in

**Comment by vozille** [comment]
my base path is http://localhost/Interface, where Interface = Web Interface folder

**Comment by pushkar8723** [comment]
Then set SITE_URL as follows:
define("SITE_URL", "http://" . $_SERVER['HTTP_HOST'] . "/Interface");

**Comment by vozille** [comment]
I deleted the files and set up again like you said here, but I still get the same problems

**Comment by vozille** [comment]
Not found errors

**Comment by pushkar8723** [comment]
Can you paste your apache access and error logs here?

**Comment by vozille** [comment]
Access log:
http://pastebin.com/5rwHYPY7

Error log doesnt show anything related to this project

**Comment by vozille** [comment]
You know, I just tried this in wamp server and everything works real smooth , unfortunately ubuntu still doesnt work :|

**Comment by vozille** [comment]
Thanks to that running in wamp I fixed issues with apache. Thanks for your quick reply and help too :)

**Comment by pushkar8723** [comment]
I am happy to know that your problem is solved. Still form this is issue its not clear what problem was there in configuration and how you fixed it.
Please leave a short description below. It will help others who might face same problem :)
Thanks

**Comment by vozille** [comment]
Check if virtual directory support is enabled in phpinfo() , if not, enable it by editing the apache2.conf file

**Comment by Bahodir94** [comment]
hello i have some problem with Internal Server Error 500.
when I created .htaccess file site isn't work now!

**Comment by Bahodir94** [comment]
please help me! I like this judge system and design! I want to use in my university for my students. 
I'm a student too!
